import type { Metadata } from "next";
import localfont from "next/font/local"
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png?v=4']
  }
};

const druk = localfont({
  src:[{
    path:"../../public/fonts/VT323-Regular.ttf",
    weight:"600",
  },],
  variable:"--font-druk",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${druk.variable} dark`}>

      <body className="font-druk">
        
        {children}
      </body>
    </html>
  );
}
